---
- name: Randomize password for ansible_client user
  hosts: all
  become: yes
  tasks:
    - name: Generate a random password on the control node
      delegate_to: localhost
      run_once: true
      community.general.password:
        length: 16
        special: true
      register: random_password

    - name: Display the generated password
      delegate_to: localhost
      run_once: true
      debug:
        msg: "The new password for ansible_client is: {{ random_password.password }}"

    - name: Hash the generated password
      community.crypto.openssl_passwd:
        password: "{{ random_password.password }}"
      register: hashed_password

    - name: Change password for ansible_client user on managed nodes
      user:
        name: ansible_client
        password: "{{ hashed_password.crypted_password }}"

